[theme]
primaryColor = "#1D1D1F"  # Colore primario scuro
backgroundColor = "#FFFFFF"  # Sfondo bianco
secondaryBackgroundColor = "#F5F5F7"  # Sfondo secondario leggermente grigio
textColor = "#000000"  # Testo nero
font = "sans serif"  # Font sans-serif
